### PR TITLE
Adding some features // See description.

### PR DESCRIPTION
**Pull request by Arsukeey**
You can now add a note to "1d" and I'm adding the "Next tuesday / sunday / anything" note

### CODE REVIEW

**Comment by aesophor** [comment]
Great job, thanks! I'll take a look asap!

**Comment by aesophor** [comment]
I think there is a potential bug. For example, suppose today is Monday, and if a user type "3d", then it will show "Next Thursday". Maybe we should add an extra if statement to check if it should be "This" or "Next" Thursday? What do you think?

**Comment by Arsukeey** [comment]
Oh, we can easily fix this. I made that mistake because in my country we talk like that. Sorry for the confusion, haha. We just have to change the array.

I'm also looking forward into removing multiple notes at the same time, like 

`-r 0 1`  or `-r -a` to clear all notes

As we can't edit files because that would change the date I'm just going to add that.

**Comment by Arsukeey** [comment]
Done everything I said above.

**Comment by aesophor** [comment]
I also implemented user configuration:
```
detail_mode = true / false
week_start_day = Sun / Mon
```
When detail_mode is false, strings like "Next Monday", "This Friday"... etc will not show, and vice versa.
week_start_day is self explanatory.

**Comment by Arsukeey** [comment]
Nice.

**Pull request merged**
