### PR TITLE
-Added Support for Timestamps

### PR DESCRIPTION
**Pull request by LouisKlimek**

### CODE REVIEW

**Comment by aesophor** [comment]
Thank you! This is a nice and useful feature.

Just one little thing: Adding a todo item without timestamp will show 00:00:00 by default, which (in my opinion) could be a bit verbose and distracting. Perhaps this feature can be implemented as togglable via config?

**Comment by LouisKlimek** [comment]
> 
> 
> Thank you! This is a nice and useful feature.
> 
> Just one little thing: Adding a todo item without timestamp will show 00:00:00 by default, which (in my opinion) could be a bit verbose and distracting. Perhaps this feature can be implemented as togglable via config?

Making it togglable + showing just nothing like before, when the timestamp is 00:00:00 maybe?
I could implement that quickly if you like.

**Comment by LouisKlimek** [comment]
> 
> 
> > Thank you! This is a nice and useful feature.
> > Just one little thing: Adding a todo item without timestamp will show 00:00:00 by default, which (in my opinion) could be a bit verbose and distracting. Perhaps this feature can be implemented as togglable via config?
> 
> Making it togglable + showing just nothing like before, when the timestamp is 00:00:00 maybe?
> I could implement that quickly if you like.

Done :)

**Comment by aesophor** [comment]
Thank you!

(Sorry for late reply, I got my wisdom tooth extracted the other day, and I didn't feel well until today)

**Pull request merged**
