### PR TITLE
Code clean-up: Separating out functions, improving docs, and tweaking colors

### PR DESCRIPTION
**Pull request by Steampunkery**
In this PR I fix a few things that have been bugging me. 

# Colors
* When using color mode, the colors have a kind of ugly grey back ground. I removed this from the escape codes and tweaked the colors to be a bit more vibrant. 
* I added a few more colors, along with some color logic for coloring in strings in a new function

# Docs
* I wrote docs for every function I added
* I just corrected some small things I saw as I was working

# Functions
* I moved some common code into functions, for example, taking input (from args or cmd line) should now be done with `take_input()`, and adding color to a string should be done with `maybe_color_str()`

### CODE REVIEW

**Comment by RewoundVHS** [comment]
Could you post a screenshot of this “ugly grey background”? I haven’t seen this.

**Comment by Steampunkery** [comment]
Here's a screenshot
gray

**Comment by Steampunkery** [comment]
With this PR, the same config and datafile output looks like this:
gray

**Comment by RewoundVHS** [comment]
Hi! Great idea to use different colors for due today and past due. I took a look at your version and I personally don't find it aesthetically pleasing when colors are statically defined instead of given by the terminal colors. From a theming perspective I think it would be nicer to use the following as the colors.

```
index_color = '\x1b[34m{}\x1b[0m'
date_color = '\x1b[32m{}\x1b[0m'
due_color = '\x1b[31m{}\x1b[0m'
today_color = '\x1b[36m{}\x1b[0m' 
```

Here is a screenshot todo using these colors

2018-11-02-235830_1600x900_scrot

**Comment by Steampunkery** [comment]
Huh, I had no idea that terminal colors worked that way! I'll make the relevant changes after some testing. Since my original idea for `today_color` was to catch the eye without being red (reserved for DUE!), I decided to accept your changes except for `today_color`, which becomes `\x1b[33m{}\x1b[0m`, which is yellow. I was going to use bright yellow, but it doesn't look very good.

**Comment by aesophor** [comment]
I love the way you refactor it! Thanks a lot! :tada: 
Perhaps you could also look into the **Contributors** section in README.md? Like adding what you have done.

Cheers!

**Pull request merged**
